name: Flutter CI

# This workflow is triggered on pushes to the repository

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Setup the flutter environment
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .
    - run: flutter build apk --debug --split-per-abi
    # Upload generated apk's to the artifacts
    - name: Create a release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.token }}
